spring:
  application:
    name: TripPamineBE
  datasource:
    # 오라클 JDBC 드라이버
    driver-class-name: oracle.jdbc.OracleDriver
    # URL 구성: jdbc:oracle:thin:@<TNS_ALIAS>?TNS_ADMIN=<지갑_ZIP파일_경로>
    url: jdbc:oracle:thin:@trippamine_high?TNS_ADMIN=./TripPamineBE/src/main/resources/wallets
    # DB 계정 정보
    username: TripPamine
    password: TeamProj1234

  # 애플리케이션 실행 시 DDL(테이블 생성/수정) 자동 관리 옵션
  jpa:
    hibernate:
      ddl-auto: validate
      # SQL 출력 및 포맷팅 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true             # 콘솔에 출력되는 SQL을 보기 좋게 줄바꿈
        highlight_sql: true          # 콘솔 SQL에 색상(하이라이팅) 부여
        use_sql_comments: true       # Executing 어떤 쿼리/메서드인지 주석 표시
        default_batch_fetch_size: 100 # 성능 최적화 (N+1 문제 방지용 지연 로딩 일괄 조회)

server:
  port: 8080

  jwt:
    secret: {"JWT_SECRET_KEY"}
    expiration: 3600000



